### PR TITLE
Fix merge error

### PR DESCRIPTION
**Pull request by wenkaidu**

### CODE REVIEW

**Comment by nusislam** [comment]
Are we supposed to run CI on this PR?

**Comment by wenkaidu** [comment]
> Are we supposed to run CI on this PR?

CI has been broken for a long time. Care to fix it?

**Comment by PedramAlizadeh** [comment]
This fix was due to introduction of "totalProcs" in the code, right?

**Comment by wenkaidu** [comment]
> This fix was due to introduction of "totalProcs" in the code, right?

yes

**Pull request merged**
